DROP TABLE IF EXISTS selected_dishes CASCADE;
CREATE TABLE selected_dishes (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES orders (id) ON DELETE CASCADE,
  menu_item_id INTEGER REFERENCES menu_items (id) ON DELETE CASCADE
);
